---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secret
spec:
  selector:
    matchLabels:
      app: hello-secret
  template:
    metadata:
      labels:
        app: hello-secret
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: USER1NAME
            valueFrom: 
              secretKeyRef:
                key: USERNAME
                name: app1
          - name: USER1PASSWORD 
            valueFrom: 
              secretKeyRef: 
                key: USERPASSWOD
                name: app1
