#
# Installation du service apache sur tous les workers
# 2020-11-04
#
# @autor Desire NTAMBIYE (desire.ntambiye@capgemini.com)
#

- name: Installation et configuration du service apache
  hosts: all
  gather_facts: yes
  become: yes
 

  tasks:

  - name: Installation du serveur Apache
    package:
      name: '{{ service_apache }}'
      state: present
 
  - name: Activation du serveur Apache
    systemd:
      name: '{{ service_apache }}'
      state: started
      enabled: yes

  - name: Copie du fichier files/index.html
    copy:
      src: index.html
      dest: /var/www/html/

  - name: Afficher le system d'exploitation
    debug:
      msg : Voici l'OS de la machine {{ ansible_distribution }} {{ ansible_architecture }}
