#
#
# @autor DESIRE NTAMBIYE (desire.ntambiye@capgemini.com)
#
# 2020-11-03 
#

---
- name : Create a new user to all machines
  hosts : all
  become : yes
  vars: 
    redhat_users:
      - toto
      - redneck
      - kathie

  tasks: 

    - name: Create ubuntu users using loop and condition  
      user: 
        name : "{{ item }}"
        state : present 
      loop : "{{ nv_users }}"
      when : "'ubuntu' in group_names"

    - name: Create redhat users using loop and condition
      user: 
        name : "{{ item }}"
        state: present
      loop: "{{ redhat_users }}"
      when: "'redhat' in group_names"
...
