#
# @autor DESIRE NTAMBIYE (desire.ntambiye@capgemini.com)
#
# 2020-11-03 
#

---
- name : Create a new user to all machines
  hosts : all
  become : yes

  tasks: 

    - name: Retrieve varibale from encrypted file
      include_vars:
        file: secret

    - name: Display the encrypted variable 
      debug:
        msg : "{{secret}}"
...
