---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-match
spec:
  replicas: 3
  selector:
    matchExpressions:
      - 
        key: app
        operator: in
        values:
          - hello-world-match
  template:
      metadata:
        labels:
          app: hello-world-match
      spec:
        containers:
         - name: hello-app
           image: gcr.io/google-samples/hello-app:1.0
           ports:
             - protocol: TCP
               containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-match-service
spec:
  selector:
    app: hello-world-match
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080